version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    volumes:
      - storage:/var/www/storage
      - bootstrap_cache:/var/www/bootstrap/cache
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    networks:
      - laravel
    environment:
      APP_NAME: ${APP_NAME}
      APP_DEBUG: ${APP_DEBUG}
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: mysql
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      APP_KEY: ${APP_KEY}
      APP_ENV: ${APP_ENV}
      TZ: America/Los_Angeles # Set timezone here

  mysql:
    image: mysql:8
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - public_storage:/var/www/public/storage # Share volume with Nginx
    depends_on:
      - app
    networks:
      - laravel

volumes:
  dbdata:       # Database data
  storage:      # Laravel storage directory
  bootstrap_cache: # Laravel bootstrap cache directory
  public_storage:  # User uploaded files or other public files

networks:
  laravel:
    driver: bridge